#!/usr/bin/env python3

import colors as c
import time

print(c.clear)

while True:
    for verse in range(5):
        for badger in range(12):
            print(c.base0 + 'badger!')
            time.sleep(0.4)
        if verse < 4: 
            for mushroom in range(2):
                print(c.red + 'muuushroom!')
                time.sleep(0.8)

    print(c.yellow + 'ooh its a snake oohh its a snake!')
    time.sleep(1)
