#!/usr/bin/env python3

import colors as c

print(c.red + "Who would cross the bridge of death, must answer me these questions 3, ere the other side he see.")

def prompt(question):
    print(question)
    answer = input("> ")
    return answer

name = prompt("What is your name?")
quest = prompt("What is your quest?")

if name == "lanceolot":
    color = prompt("What is you faovrite colour?")
    if color == "blue":
        print("ok off you go.")
    else:
        print("paaacheeewww!! off you go baaccaa you have been cast into the gorge of 10,003 upturned lances and 1 spoon.")


elif name == "robin":
    capital = prompt("What is the capital of Yemmen? heh heh heh.")
    if capital == "that doesnt exist":
        print("fuwee ok off you pop then.")
    else:
        print("paaacheeewww!! off you go baaccaa you have been cast into the gorge of 10,003 upturned lances and 1 spoon.")


elif name == "arthur":
    swallow = prompt("what is the air speed volocity of an unladen swallow.")
    if swallow == "african or european":
        print("What i dont know that. pppechheew ahhhhh!!")
    else:
        print("paaacheeewww!! off you go baaccaa you have been cast into the gorge of 10,003 upturned lances and 1 spoon.")        
