#!/usr/bin/env python3

from util import ask
import colors as c
import time as t
import random


print(c.clear)
print(c.base3 + 'samuel lucas is not responsible for anything in this quiz.' + c.reset)
print(c.yellow + 'welcome to the quiz game for unicorn hunters.' + c.reset)


def q1():
    print(c.red  + 'What is the color of the pink fluffy unicorn?')
    pink == input('> ').strip().lower()
    if pink.startwith("pink"):
        return True
    else:
        return False

def q2():
    print(c.red + 'What is the pink fluffy unicorn dancing on?')
    rainbows == input('> ').strip().lower()
    if rainbows.startwith("rainbows"):
        return True
    else:
        return False

def q3():
    print(c.red + 'How do we describe the pink fluffy unicorns fur?')
    smiles == input('> ').strip().lower()
    if smiles.startwith("smile"):
        return True
    else:
        return False

questions = [q1,q2,q3]

while questions:
    question = random.choice(questions)
    answer = question()
    if answer:
        questions.remove(question)
