#!/usr/bin/env python3

import random

import colors as c

score = 0

print(c.clear)
print(c.blue + 'Welcome to the redstone quiz.' + c.reset)

def q1():
    print(c.reset + c.blue + 'What level is redstone most common on?')
    answer = input('> ')
    if answer == "16":
        print(c.reset + c.green + 'Correct.')
        return 1
    else:
        lose()
        return 0
    
def q2():
    print(c.reset + c.blue + 'How many blocks does a redstone pulse travel?')
    answer = input('> ')
    if answer == "15":
        print(c.reset + c.green + 'Correct.')
        return 1
    else:
        lose()
        return 0

def q3():
    print(c.reset + c.blue + 'How many blocks can one piston push?')
    answer = input('> ')
    if answer == "12":
        print(c.reset + c.green + 'Correct.')
        return 1
    else:
        lose()
        return 0

def win():
    print(c.reset + c.green + 'You have completed the redstone quiz.')

def lose():
    print(c.reset + c.red + 'You are wrong.')

def ask(question):
    print(question)
    return input('> ').strip().lower()

questions = [q1,q2,q3]

while questions:
    question = random.choice(questions)
    points = question()
    score += points
    if points:
        questions.remove(question)
print(c.reset + c.green + 'You have completed the test, score: ', score)
