#!/usr/bin/env python3

import random
import colors as c

print(c.clear)
print(c.green + '''This is a fight quiz the text in blue tells you what
the other knight is doing if he swing left block left. Blocks, stabs and
Cleaves have different answers. Cut = Block, Stab = Deflect,
and Cleave = Cross block. Don't wait to long or
he get desperate and make rash moves.
That is all you should need to know have fun.''')

print(c.blue + '''
You are a knight from a far off land. You are traveling through a village and you
stop to look at a platform with 5 knights standing on it challenging near by people.
One of the knights looks your way and says You fight me in the arena.
You have been challenged to a dual by the other knight.
type what you want to do bellow.
''')


try:

    score = 0

    def q1():
        print(c.orange  + '(accept or decline)')
        answer = input(c.base2 + '> ').strip().lower()
        if "accept" in answer:
            print(c.clear)
            print(c.green + 'You have accepted the dual.')
            return 1
        else:
            print(c.red + 'The other knight replies "Fine run you coward."')
            return 0
            exit()

    def q2():
        print(c.blue + 'he swing to the left.')
        print(c.orange  + '(block left, block right, or attack)')
        answer = input(c.base2 + '> ').strip().lower()
        if "block left" in answer:
            print(c.clear)
            print(c.green + 'You blocked his cut.')
            return 1
        else:
            print(c.red + 'The other knight cuts your side.')
            return 0
            exit()

    def q3():
        print(c.blue + 'he thrusts right.')
        print(c.orange  + '(deflect left, deflect right, or attack)')
        answer = input(c.base2 + '> ').strip().lower()
        if "deflect right" in answer:
            print(c.clear)
            print(c.green + 'You blocked his thrust')
            return 0
        else:
            print(c.red + 'The other knight ran you through.')
            return 0
            exit()

    def q4():
        print(c.blue + 'instead of attacking he takes a defensive poster')
        print(c.orange  + '(attack, or take a defensive poster)')
        answer = input(c.base2 + '> ').strip().lower()
        if "attack" in answer:
            print(c.clear)
            print(c.green + '''You stab the other knight in the chest
            he is now wounded and will attack less.''')
            return 1
        else: 
            print(c.blue + 'he thrusts left.')
            print(c.orange  + '(deflect left, deflect right, or attack)')
            answer = input(c.base2 + '> ').strip().lower()
            if "deflect left" in answer:
                print(c.clear)
                print(c.green + 'You deflected his thrust')
                return 1
            else:
                print(c.red + 'the other knight ran you through.')
                return 0
                exit()

    def q5():
        print(c.blue + 'he swings right and then thrusts left')
        print(c.orange  + '(block right deflect left, block left block right right, or attack)')
        answer = input(c.base2 + '> ').strip().lower()
        if "block right deflect left" in answer:
            print(c.clear)
            print(c.green + '''the other knight is exhausted and will attack less.''')
            return 1
        else:
            print(c.red + 'The other knight ran you through.')
            return 0
            exit()


    def q6():
        print(c.blue + 'he swings to the left.')
        print(c.orange  + '(block left, block right, or attack)')
        answer = input(c.base2 + '> ').strip().lower()
        if "block left" in answer:
            print(c.clear)
            print(c.green + 'You blocked his cut.')
            return 1
        else:
            print(c.red + 'The other knight cuts your side.')
            return 0
            exit()


    def q7():
        print(c.blue + 'instead of attacking the other knight lowers his sword and waits')
        print(c.orange  + '(attack, or take a defensive poster)')
        answer = input(c.base2 + '> ').strip().lower()
        if "attack" in answer:
            print(c.clear)
            print(c.green + '''You stab the other knight in the chest
                            and he dies you win the dual.''')
            return 1
            exit()
        else: 
            print(c.blue + 'he cleaves down.')
            print(c.orange  + '(cross block up, block  right, block left, or attack)')
            answer = input(c.base2 + '> ').strip().lower()
            if "cross block up" in answer:
                print(c.green + 'You blocked his cut')
                return 1
            else:
                print(c.red + 'the other knight cleaves you from above and you die.')
                return 0
                exit()

    def q8():
        print(c.blue + 'instead of attacking the other knight waits')
        print(c.orange  + '(attack, or take a defensive poster)')
        answer = input(c.base2 + '> ').strip().lower()
        if "attack" in answer:
            print(c.clear)
            print(c.green + '''You stab the other knight in the chest.''')
            return 1
            exit()
        else:
            print(c.red + '''the other knight made a desperate move
                             and cleaves you from above.''')
            return 0
            exit()
    
    q1()

    questions = [q2,q3,q4,q5,q6,q7,q8]

    while questions:
        question = random.choice(questions)
        points = question()
        score += points
        if points:
            questions.remove(question)
    print(c.reset + c.green + '''You have completed the dual.
                                If your score was 6,5 you are wounded and die later of infection.
                                If your score was 8,7, you win with only minor or no injurys.
                                if your score was 4,0 you die a painfull death as the knight laughs at your corpse.
                                score: ''', score)

except KeyboardInterrupt:
    print(c.clear)
    exit()
