#!/usr/bin/env python3

import time
import colors as c

hundredths = 0
seconds = 0
minutes = 0
hours = 0

while True:
    try:
        print(c.clear + c.base3 + 'Print Ctrl C to quit.')
        print('hundredths, seconds and minutes.')
        print(hundredths)
        print(seconds)
        print(minutes)
        time.sleep(0.01)
        hundredths += 1
        if hundredths == 100:
            hundredths = 0
            seconds += 1
        if seconds == 60:
            seconds = 0
            minutes += 1
    except KeyboardInterrupt:
        print(c.clear)
        exit()
