#!/usr/bin/env python3
import random

answers =[
    "yes",
    "no",
]

while True:
    question = input("> ")
    if question == "bye":
        print("ok bye")
        exit()
    print(random.choice(answers))
