#!/usr/bin/env python3

import time

while True:
    print("badger")
    time.sleep(0.5)
    print("badger")
    time.sleep(0.5)
    print("badger")
    time.sleep(0.5)
    print("oohh its a snake")

