#!/usr/bin/env python3

def live():
    print("alright then off you go.")

def die():
    print("ppppaaaaaaccckkkcccchhhooooo!!!!")
    exit()

name = input("what is your name?" + " > ") 
quest = input("what is your quest?" + " > ")

if name == "lanceolot":
    color = input("what is your favorite color?" + " > ")
    if color == "blue":
        live()
    else:
        die()


